@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzk5MjgyOTN9.0vNMvApqHAkZx4wJKIjhok4mG6Ep12pTqFV-4vB_l8o

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
"name" : "test users",
"email": "test1@test.com",
"password": "password",
"password_confirmation": "password"
}

### Todos Index
GET http://localhost:3000/to_do.json


### Todos Show
GET http://localhost:3000/to_do.json

### Todos Create
POST http://localhost:3000/to_do.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
"user_id": 1,
"title": "Do Dishes",
"description": "Washes dishes by hand",
"deadline": "Tonight",
"completed": "false"
}

###ToDo Update
PATCH http://localhost:3000/to_do/1.json
Content-Type: application/json

{"completed": "Completed!"}

### Category Create
POST http://localhost:3000/category.json
Content-Type: application/json

{
"name": "House Work"
}

### CategoryToDo Create
POST http://localhost:3000/category_to_dos.json
Content-Type: application/json

{ "category_id":1,
"todo_id": 1
}

### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "test1@test.com",
"password": "password"
}

### Category To Do Create

POST http://localhost:3000/category_to_do.json
Content-Type: application/json

{"category_id": 2,
 "todo_id": 1}